# Agenda
-

In [4]:
import pandas as pd

In [5]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [8]:
"Monal".replace("M","MM")

'MMonal'

In [9]:
df['Name'].str.replace("Mr.","Sir",regex = False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [10]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [11]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [12]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [13]:
start = df.loc[1, 'Name'].find("(")

In [14]:
end = df.loc[1, 'Name'].find(")")

In [15]:
df.loc[1, 'Name'][0:start] + df.loc[1, 'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [16]:
def removing_substring(name):
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start] + name[end+1:0]
    new_name = new_name.strip()# to remove the same spaces (optinal)
    return new_name

In [17]:
df["shortened_name"] = df['Name'].apply(removing_substring)
df["shortened_name"].head()

0          Braund, Mr. Owen Harri
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Lain
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henr
Name: shortened_name, dtype: str

In [18]:
df.loc[1,'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [19]:
df.loc[1, 'shortened_name']

'Cumings, Mrs. John Bradley'

In [20]:
# Replace Substrings with regex : regular expression

# * means zero or more
# . match any character
#"r\(.*\)" ---> regex pattern

# windows : \\ ---> "\\(.*\\)"

df['Name'].str.replace(r"\(.*\)", "HELLO",regex = True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

| Part  | Meaning                                                         |
| ----- | --------------------------------------------------------------- |
| r     | Raw string literal -- tells python not to interpret \ as escape |
| \(    | Escaped ( -- matches a literal opening paranthesis              |
| .*    | Dot . matches any character, and * means zero or more           |
| \)    | Escaped ) -- matches a literal closing paranthesis              |

In [21]:
# hello@ghail@abc.com

# own python logic

# regex pattern

In [22]:
# optional as it is complex better use ai for help than learning and remebering everything about regex
import re

In [23]:
def is_valid_email(email):
    # Breakdown of the regex pattern:
    # r'          -> Indicates a "raw" string (treats backslashes literally)
    # ^           -> Start of the string
    # [a-zA-Z0-9._%+-]+ -> Matches the username: letters, numbers, and specific symbols (+ one or more times)
    # @           -> Matches the literal "@" symbol
    # [a-zA-Z0-9.-]+    -> Matches the domain name: letters, numbers, dots, or hyphens (+ one or more times)
    # \.          -> Matches a literal dot "." (the backslash "escapes" it)
    # [a-zA-Z]{2,} -> Matches the extension (TLD): letters only, minimum of 2 characters long
    # $           -> End of the string
    regex = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # re.fullmatch checks if the ENTIRE string follows the pattern from ^ to $
    if re.fullmatch(regex, email):
        return True
    return False

# Test cases
emails = ["user@example.com", "my.name+alias@work-place.org", "invalid-email@com", "hello@ghail@abc.com"]
for e in emails:
    # Prints the email and whether the function returned True (valid) or False (invalid)
    print(f"{e}: {'valid' if is_valid_email(e) else 'Invalid'}")

user@example.com: valid
my.name+alias@work-place.org: valid
invalid-email@com: Invalid
hello@ghail@abc.com: Invalid

## Split and Access Elements

In [24]:
df["Name"][0]

'Braund, Mr. Owen Harris'

In [25]:
df["Name"].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [26]:
df["Name"].str.split( ).str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [27]:
df["Name"].str.split( ).str[0][0]

'Braund,'

## Strip Spaces

In [28]:
df["Name"].str.strip( )

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [29]:
df["Name"].str.lstrip( )

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [30]:
df["Name"].str.rstrip( )

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [31]:
# Find Positin of Substring

In [32]:
df["Name"].str.find("Mr" )

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [33]:
# "Miss"
# Count passengers with "miss" in name

count = df['Name'].str.contains("Miss").sum()
print("Number of passengers with 'Miss' in their name :", count)

Number of passengers with 'Miss' in their name : 182

In [34]:
data = {
    "Name" : ['John Doe', 'Jane Smith', 'Emily Johnson', 'Robert Brown', 'Anna-Marie Lee'],
    "Email" : ['john@example.com', 'jane.smith@work.org', 'emily_j@data.net', 
               'robertb@yahoo.com', 'anna.lee@company.co']
}

df = pd.DataFrame(data)

In [35]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [36]:
df["Name"].str.pad(width=20, side='left', fillchar='-')

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

## Categorical Data in Pandas

### What is Categorical Data?
Categorical data is textual or labelled data that represents discrete categories

In [37]:
class_data = {
    "Name" : ["a", "b", "c", "d"],
    "Groups" : ["G1", "G2", "G3", "G4"]
}

In [38]:
class_df = pd.DataFrame(class_data)

In [39]:
class_df

  Name Groups
0    a     G1
1    b     G2
2    c     G3
3    d     G4

In [40]:
# df["Groups"] > "G4"

In [41]:
# G3, G1, G2, G4 --> Higher to Lower
# df['Groups'] > "G4"
# G1 > G4 --> True

In [42]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [43]:
class_df['Groups_categ'] = pd.Categorical( # either we can save it into the groups category or save it in a new column here i saved it in 'Groups categ'.
    class_df['Groups'],
    categories = ['G3', 'G1', 'G2', 'G4'], # custom order from Lower to Higher
    ordered = True
)

In [44]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4 non-null      str
 1   Groups        4 non-null      str
 2   Groups_categ  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [45]:
class_df['Groups_categ'].cat.categories # we used .cat bcz it is category datatype

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [46]:
class_df['Groups_categ'] >=  'G4'

0    False
1    False
2    False
3     True
Name: Groups_categ, dtype: bool

In [47]:
df = pd.read_csv(titanic_dataset_github_url)

In [48]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [50]:
df['Embarked'].unique() # the port where a passenger boarded the ship, indicated by a single - letter code.
# C (Cherbourg)
# Q (Queenstown)
# S (Southampton)

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [51]:
df['Embarked'] = df['Embarked'].fillna('N')

In [52]:
df['Embarked'].unique()
# C (Cherbourg) -------> 1000000
# Q (Queenstown) ------> 5000000
# S (Southampton) -----> 0100000
# N (Not provided) ----> 0000000
# N, S, C, Q

# Find all the passengers cpaital spending > 100000 > S

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [53]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [54]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [55]:
df['Embarked_cust_cat'] = pd.Categorical(df['Embarked'], categories = ['N', 'S', 'C', 'Q'], ordered = True)

In [56]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [57]:
df['Embarked_cust_cat'] > 'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [58]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [59]:
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [60]:
# df['Sex']

# Convert the values of sex column and encode them in 0 & 1

df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [61]:
df['Sex_cat'] = df['Sex'].astype('category').cat.codes
                      # or
df['Sex_cat'] = df['Sex'].replace(['female','male'], [0,1])
                      # or
df['Sex_cat'] = df['Sex'].apply(lambda Sex: 1 if Sex == 'male' else 0)

In [62]:
df['Sex_cat'].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex_cat, dtype: int64

##  Date Functionality in Pandas

In [63]:
df = pd.DataFrame({
    'event' : ['Concert', 'Conference', 'Wedding'],
    'date' : ['2025-01-01', '2025-03-15', '2025-07-20']
})

In [ ]:
df.info()
# the date is also string so

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [65]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [ ]:
df['date_pandas'] = pd.to_datetime(df['date'])
#format : optinal format (eg. '%d/%m/%y')

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [68]:
df.head()

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [69]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [70]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [72]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [74]:
df['date_pandas'].dt.month_name()

0    January
1      March
2       July
Name: date_pandas, dtype: str

In [75]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [76]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

## Creating Date time Ranges

Other frequencies:

'M' ---> month end

'MS' ---> month start

'W' ---> weekly

'H', 'T', 's' ---> hour, minute, second

In [81]:
pd.date_range(start = '2026-02-01', end = '2026-02-10', freq = 'D')

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [82]:
pd.date_range(start = '2026-02-01', end = '2026-02-10', freq = 'ME')

DatetimeIndex([], dtype='datetime64[us]', freq='ME')

In [83]:
pd.date_range(start = '2026-02-01', end = '2026-02-10', freq = 'MS')

DatetimeIndex(['2026-02-01'], dtype='datetime64[us]', freq='MS')

In [86]:
pd.date_range(start = '2026-02-01', end = '2026-02-10', freq = 'W')

DatetimeIndex(['2026-02-01', '2026-02-08'], dtype='datetime64[us]', freq='W-SUN')

In [87]:
## Date Arithmetic

In [88]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days = 7)

In [89]:
pd.Timedelta(days = 7)

Timedelta('7 days 00:00:00')

In [94]:
df.head()

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [96]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [104]:
pd.Timestamp.today()

Timestamp('2026-03-17 17:59:15.169135')

In [105]:
df.head()

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -441 days +06:05:04.432484
1  Conference  2025-03-15  2025-03-15 2025-03-22 -368 days +06:05:04.432484
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -241 days +06:05:04.432484

# PANDAS COMPLETED

# GIT 
- Tool to manage the code(code version control tool) by creating checkpoints or versions.
- Seperates the code by 'Branches'.
- GIT works on project basis